import "server-only";
export type RateLimitResult={allowed:boolean;remaining:number;retryAfterSeconds?:number};
export interface RateLimitStore{increment(key:string,limit:number,windowMs:number):Promise<RateLimitResult>;cleanup?():Promise<void>}
type Entry={count:number;resetAt:number};
export class RedisRateLimitStore implements RateLimitStore{constructor(private readonly url:string,private readonly token:string){}async increment(key:string,limit:number,windowMs:number):Promise<RateLimitResult>{const script="local c=redis.call('INCR',KEYS[1]);if c==1 then redis.call('PEXPIRE',KEYS[1],ARGV[1]) end;local t=redis.call('PTTL',KEYS[1]);return {c,t}";const response=await fetch(this.url,{method:"POST",headers:{authorization:`Bearer ${this.token}`,"content-type":"application/json"},body:JSON.stringify(["EVAL",script,"1",`nuvra:rate:${key}`,String(windowMs)])});if(!response.ok)throw new Error("rate_limit_store_unavailable");const body=await response.json() as{result?:[number,number]};const[count,ttl]=body.result||[];if(typeof count!=="number")throw new Error("rate_limit_store_unavailable");return{allowed:count<=limit,remaining:Math.max(0,limit-count),retryAfterSeconds:count>limit?Math.max(1,Math.ceil((ttl||windowMs)/1000)):undefined}}}
export class MemoryRateLimitStore implements RateLimitStore{private entries=new Map<string,Entry>();async increment(key:string,limit:number,windowMs:number){const now=Date.now();const current=this.entries.get(key);if(!current||current.resetAt<=now){this.entries.set(key,{count:1,resetAt:now+windowMs});return{allowed:true,remaining:limit-1}}current.count+=1;return{allowed:current.count<=limit,remaining:Math.max(0,limit-current.count),retryAfterSeconds:Math.ceil((current.resetAt-now)/1000)}}async cleanup(){const now=Date.now();this.entries.forEach((value,key)=>{if(value.resetAt<=now)this.entries.delete(key)})}}
let store:RateLimitStore=new MemoryRateLimitStore();
export function configureRateLimitStore(next:RateLimitStore){store=next}
export function checkRateLimit(key:string,limit:number,windowMs:number){return store.increment(key,limit,windowMs)}
