const test=require("node:test");const assert=require("node:assert/strict");const fs=require("node:fs");const path=require("node:path");const Module=require("node:module");const ts=require("typescript");const root=path.resolve(__dirname,"..");const originalResolve=Module._resolveFilename,originalLoad=Module._load;Module._resolveFilename=function(request,parent,isMain,options){if(request.startsWith("@/"))request=path.join(root,request.slice(2));return originalResolve.call(this,request,parent,isMain,options)};Module._load=function(request,parent,isMain){if(request==="server-only")return{};return originalLoad.call(this,request,parent,isMain)};require.extensions[".ts"]=function(module,filename){const source=fs.readFileSync(filename,"utf8");const output=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022,esModuleInterop:true,moduleResolution:ts.ModuleResolutionKind.NodeJs},fileName:filename}).outputText;module._compile(output,filename)};
const{PrismaClient}=require("@prisma/client");const prisma=new PrismaClient();const{SubscriptionService}=require("../services/billing/subscription-service.ts");const{MockBillingProvider}=require("../services/billing/mock-billing-provider.ts");const{canConsume}=require("../lib/server/usage.ts");const{roleCan}=require("../lib/access-policy.ts");const cleanup=[];
async function fixture(role="owner"){const suffix=crypto.randomUUID();const user=await prisma.user.create({data:{email:`billing-${suffix}@test.local`,passwordHash:"test"}});const organization=await prisma.organization.create({data:{name:"Billing",slug:`billing-${suffix}`,memberships:{create:{userId:user.id,role}}}});cleanup.push({userId:user.id,organizationId:organization.id});return{user,organization,service:new SubscriptionService(new MockBillingProvider())}}
async function addBusinesses(organizationId,count){for(let i=0;i<count;i++)await prisma.business.create({data:{nombre:`Business ${i}`,rubro:"Test",organizationId}})}

test("FREE respeta límites existentes",async()=>{const f=await fixture();await addBusinesses(f.organization.id,1);assert.equal(await canConsume(f.organization.id,"businesses"),false);const summary=await f.service.summary(f.organization.id);assert.equal(summary.subscription.plan,"FREE");assert.equal(summary.usage.businesses.remaining,0)});
test("trial configurable comienza y al vencer vuelve a FREE",async()=>{const f=await fixture();const now=new Date("2026-01-01T00:00:00Z");const trial=await f.service.startTrial({actorUserId:f.user.id,organizationId:f.organization.id,plan:"PRO",now});assert.equal(trial.status,"trialing");assert.equal(trial.plan,"PRO");const expired=await f.service.getSubscription(f.organization.id,new Date("2027-01-01T00:00:00Z"));assert.equal(expired.status,"expired");assert.equal(expired.plan,"FREE");assert.equal((await prisma.organization.findUnique({where:{id:f.organization.id}})).planTier,"FREE")});
test("upgrade y cambio PRO a PARTNER usan el provider central",async()=>{const f=await fixture();assert.equal((await f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"PRO"})).plan,"PRO");assert.equal((await f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"PARTNER"})).plan,"PARTNER")});
test("downgrade conserva datos y marca exceso",async()=>{const f=await fixture();await addBusinesses(f.organization.id,6);await f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"PARTNER"});await f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"PRO"});assert.equal(await prisma.business.count({where:{organizationId:f.organization.id}}),6);const summary=await f.service.summary(f.organization.id);assert.equal(summary.usage.businesses.overLimit,true);assert.equal(await canConsume(f.organization.id,"businesses"),false)});
test("PRO puede volver a FREE sin borrar recursos",async()=>{const f=await fixture();await addBusinesses(f.organization.id,2);await f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"PRO"});const free=await f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"FREE"});assert.equal(free.plan,"FREE");assert.equal(await prisma.business.count({where:{organizationId:f.organization.id}}),2);assert.equal((await f.service.summary(f.organization.id)).usage.businesses.overLimit,true)});
test("cancelación al período y reactivación preservan el plan",async()=>{const f=await fixture();await f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"PRO"});const canceled=await f.service.cancel({actorUserId:f.user.id,organizationId:f.organization.id});assert.equal(canceled.cancelAtPeriodEnd,true);assert.equal(canceled.plan,"PRO");const active=await f.service.reactivate({actorUserId:f.user.id,organizationId:f.organization.id});assert.equal(active.cancelAtPeriodEnd,false);assert.equal(active.status,"active")});
test("solo owner/admin pueden gestionar y organizaciones quedan aisladas",async()=>{assert.equal(roleCan("owner","organization.manage"),true);assert.equal(roleCan("admin","organization.manage"),true);assert.equal(roleCan("member","organization.manage"),false);assert.equal(roleCan("viewer","organization.manage"),false);const a=await fixture(),b=await fixture();assert.equal(await prisma.membership.findFirst({where:{userId:a.user.id,organizationId:b.organization.id}}),null)});
test("frontend no puede inyectar un plan desconocido",async()=>{const f=await fixture();await assert.rejects(f.service.changePlan({actorUserId:f.user.id,organizationId:f.organization.id,plan:"ENTERPRISE"}),/invalid_plan/);assert.equal((await f.service.getSubscription(f.organization.id)).plan,"FREE")});
test("webhook duplicado es idempotente y el pago es autoritativo",async()=>{const f=await fixture();const payload=JSON.stringify({id:`event-${crypto.randomUUID()}`,type:"subscription.updated",organizationId:f.organization.id,occurredAt:new Date().toISOString(),subscription:{plan:"PRO",status:"active"}});const first=await f.service.handleWebhook(payload,"mock-signature");const duplicate=await f.service.handleWebhook(payload,"mock-signature");assert.equal(first.duplicate,false);assert.equal(duplicate.duplicate,true);assert.equal((await prisma.organization.findUnique({where:{id:f.organization.id}})).planTier,"PRO")});
test("webhook con firma inválida no modifica estado",async()=>{const f=await fixture();const payload=JSON.stringify({id:"bad",type:"subscription.updated",organizationId:f.organization.id,occurredAt:new Date().toISOString(),subscription:{plan:"PARTNER",status:"active"}});await assert.rejects(f.service.handleWebhook(payload,"wrong"));assert.equal((await prisma.organization.findUnique({where:{id:f.organization.id}})).planTier,"FREE")});
test("webhook fuera de orden no revierte un estado más nuevo",async()=>{const f=await fixture();const newer=new Date("2026-06-02T00:00:00Z"),older=new Date("2026-06-01T00:00:00Z");const event=(id,date,plan)=>JSON.stringify({id,type:"subscription.updated",organizationId:f.organization.id,occurredAt:date.toISOString(),subscription:{plan,status:"active"}});await f.service.handleWebhook(event(`new-${crypto.randomUUID()}`,newer,"PARTNER"),"mock-signature");const result=await f.service.handleWebhook(event(`old-${crypto.randomUUID()}`,older,"PRO"),"mock-signature");assert.equal(result.ignored,true);assert.equal((await prisma.organization.findUnique({where:{id:f.organization.id}})).planTier,"PARTNER")});

test.after(async()=>{for(const item of cleanup.reverse()){await prisma.organization.delete({where:{id:item.organizationId}}).catch(()=>{});await prisma.user.delete({where:{id:item.userId}}).catch(()=>{})}await prisma.$disconnect()});
