import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import { businessUpdateSchema } from "../lib/business-update.ts";
import { buildAnalysisFreshness, createAnalysisInputSnapshot } from "../lib/analysis-freshness.ts";
import { buildDashboardViewModel } from "../lib/dashboard-view-model.ts";

const read = (path) => fs.readFileSync(new URL(`../${path}`, import.meta.url), "utf8");
const currentBusiness = { id: "business-1", nombre: "Café Sur", rubro: "Cafetería", ubicacion: "Palermo", ciudad: "Buenos Aires", pais: "Argentina", empleados: "2 personas", webUrl: "https://cafe.example/", instagramHandle: "https://www.instagram.com/cafesur/", noWebDeclared: false, noInstagramDeclared: false, canales: JSON.stringify(["Instagram", "WhatsApp"]), inversionMarketing: 100 };
const currentGoal = { objetivo: "Conseguir más reservas", objetivoCustom: null, magnitud: 20, plazoDias: 90, plazoLabel: "3 meses" };
const snapshot = { analysisInput: createAnalysisInputSnapshot(currentBusiness, currentGoal), businessProfile: { goal: { timeframeLabel: "3 meses" } } };
const freshness = (business = currentBusiness, goal = currentGoal, snapshotValue = snapshot) => buildAnalysisFreshness({ business, currentGoal: goal, snapshot: snapshotValue, score: { objetivo: "Conseguir más reservas", plazoDias: 90 }, strategy: { objetivo: "Conseguir más reservas" }, hasAnalysis: true, analyzedAt: "2026-08-20T10:00:00.000Z" });

test("A: un negocio sin análisis no queda marcado como desactualizado", () => assert.equal(buildAnalysisFreshness({ business: currentBusiness, currentGoal, snapshot: {}, hasAnalysis: false }).status, "no_analysis"));
test("B y C: un análisis sin cambios está vigente y conserva el objetivo analizado", () => { const result = freshness(); assert.equal(result.status, "current"); assert.equal(result.needsReanalysis, false); assert.equal(result.analyzedGoal, "Conseguir más reservas"); });
test("D: un cambio relevante del negocio marca stale sin recalcular", () => { const result = freshness({ ...currentBusiness, webUrl: "https://nuevo.example/" }); assert.equal(result.status, "stale_due_to_business_change"); assert.deepEqual(result.changedFields, ["página web"]); });
test("E: un cambio menor de descripción no marca stale", () => assert.equal(freshness({ ...currentBusiness, descripcion: "Texto actualizado" }).status, "current"));
test("F: un cambio de objetivo preserva ambos objetivos y marca stale", () => { const result = freshness(currentBusiness, { ...currentGoal, objetivo: "Aumentar la recompra" }); assert.equal(result.status, "stale_due_to_goal_change"); assert.equal(result.analyzedGoal, "Conseguir más reservas"); assert.equal(result.currentGoal, "Aumentar la recompra"); });
test("G: cambios conjuntos se distinguen de un único cambio", () => assert.equal(freshness({ ...currentBusiness, rubro: "Café y panadería" }, { ...currentGoal, plazoDias: 180 }).status, "stale_due_to_business_and_goal_change"));
test("H: los snapshots legacy incompletos no rompen", () => { const result = freshness(currentBusiness, currentGoal, { businessProfile: { businessName: "Café Sur", originalIndustry: "Cafetería", location: "Palermo", goal: { text: "Conseguir más reservas", timeframeDays: 90 } } }); assert.ok(result.status); });

test("I, J y K: PATCH acepta solo la lista permitida y exige versión", () => { const valid = businessUpdateSchema.parse({ expectedUpdatedAt: "2026-08-20T10:00:00.000Z", business: { nombre: "Nuevo nombre", noWebDeclared: true, webUrl: null } }); assert.equal(valid.business?.nombre, "Nuevo nombre"); assert.throws(() => businessUpdateSchema.parse({ expectedUpdatedAt: "2026-08-20T10:00:00.000Z", business: { organizationId: "org-b" } })); assert.throws(() => businessUpdateSchema.parse({ business: { nombre: "Sin versión" } })); });
test("L y M: schema evita contradicciones de web e Instagram", () => { assert.throws(() => businessUpdateSchema.parse({ expectedUpdatedAt: "2026-08-20T10:00:00.000Z", business: { noWebDeclared: true, webUrl: "https://example.test" } })); assert.throws(() => businessUpdateSchema.parse({ expectedUpdatedAt: "2026-08-20T10:00:00.000Z", business: { noInstagramDeclared: true, instagramHandle: "@perfil" } })); });
test("N y O: endpoint autoriza, versiona objetivos y audita sin ejecutar análisis", () => { const source = read("app/api/business/route.ts"); assert.match(source, /authorizeBusiness\(id, "business\.update"\)/); assert.match(source, /expectedUpdatedAt/); assert.match(source, /businessGoal\.updateMany/); assert.match(source, /businessGoal\.create/); assert.match(source, /business\.goal_changed/); assert.doesNotMatch(source, /runFullAnalysis|\/api\/analyze\/run/); });
test("P: la edición normaliza web e Instagram del lado servidor", () => { const source = read("app/api/business/route.ts"); assert.match(source, /normalizeEditableWebsite/); assert.match(source, /parseInstagramProfile/); assert.match(source, /\["http:", "https:"\]/); });
test("Q: viewer sigue sin permiso de escritura", () => { const policy = read("lib/access-policy.ts"); const viewer = policy.match(/viewer:[^\n]+/)?.[0] || ""; assert.match(viewer, /business\.read/); assert.doesNotMatch(viewer, /business\.update/); });

test("R y S: DashboardViewModel expone edición por permiso y estrategia histórica", () => { const raw = { ...currentBusiness, updatedAt: "2026-08-30T12:00:00.000Z", goals: [{ ...currentGoal, objetivo: "Aumentar recompra" }], scores: [{ id: "score-1", total: 60, objetivo: "Conseguir más reservas", plazoDias: 90, dimensions: [] }], diagnoses: [], strategies: [{ id: "strategy-1", objetivo: "Conseguir más reservas", actions: [] }], analysisHistory: [{ id: "history-1", createdAt: "2026-08-20T10:00:00.000Z", snapshot: JSON.stringify(snapshot), nuvraScoreTotal: 60 }], analysisRuns: [], planTier: "FREE" }; const view = buildDashboardViewModel(raw, { canUpdateBusiness: true }); assert.equal(view.business.canEditDeclaredInformation, true); assert.equal(view.canonicalStrategy?.objective, "Conseguir más reservas"); assert.equal(view.analysisFreshness.currentGoal, "Aumentar recompra"); });
test("T: el modal guarda por PATCH y no por estado local solamente", () => { const page = read("app/dashboard/negocio/page.tsx"); assert.match(page, /method: "PATCH"/); assert.match(page, /expectedUpdatedAt/); assert.match(page, /Guardar cambios/); });
test("U, V y W: dashboard, diagnóstico y estrategia muestran vigencia y reanálisis", () => { const component = read("components/dashboard/analysis-freshness-notice.tsx"); assert.match(component, /estrategia corresponde al objetivo anterior/); assert.match(component, /\/analyze\?businessId=/); for (const page of ["app/dashboard/page.tsx", "app/dashboard/diagnostico/page.tsx", "app/dashboard/estrategia/page.tsx"]) assert.match(read(page), /AnalysisFreshnessNotice/); });
test("X: la captura del análisis conserva el contexto declarado y del objetivo", () => assert.match(read("services/pipeline/run-analysis.ts"), /analysisInput: createAnalysisInputSnapshot\(business, goal\)/));
test("Y y Z: configuración mantiene solo controles reales y no duplica billing", () => { const configuration = read("app/dashboard/configuracion/page.tsx"); assert.equal((configuration.match(/<BillingPanel/g) || []).length, 1); assert.match(configuration, /IntegrationManager/); assert.doesNotMatch(configuration, /Guardar preferencias|Cambiar contraseña/); });
