"use client";
import { useDashboardData } from "@/lib/use-dashboard-data";
import { COLORS } from "@/lib/design-tokens";
import { DemoBadge, EmptyState, ErrorState, PageHeader, PageSkeleton, SectionHeader } from "@/components/ui";
import { simplifyTechnicalText, getFriendlyDimensionName } from "@/lib/simple-language-presenter";
export default function DiagnosticoPage(){
 const {diagnosis,loading,error,isDemo}=useDashboardData(); if(loading)return <PageSkeleton/>; if(error)return <ErrorState message={error}/>; if(!diagnosis)return <EmptyState title="Todavía no hay diagnóstico" description="Completá el onboarding para generar una lectura del negocio."/>;
 return <div className="page-container"><PageHeader eyebrow="Lectura del negocio" title="Diagnóstico" subtitle={<>{isDemo&&<DemoBadge style={{marginRight:8}}/>}Qué está funcionando, qué frena el objetivo y dónde conviene actuar.</>}/>
  <section style={{maxWidth:820,marginBottom:38}}><SectionHeader title="En pocas palabras"/><p style={{fontSize:16,lineHeight:1.75}}>{simplifyTechnicalText(diagnosis.summary)}</p></section>
  {diagnosis.bottleneck&&<section className="strategic-callout" style={{marginBottom:40}}><div className="page-eyebrow">La prioridad principal</div><h2 style={{fontSize:20,fontWeight:650,lineHeight:1.35}}>{getFriendlyDimensionName(diagnosis.bottleneck.dimension,diagnosis.bottleneck.dimension)}: {simplifyTechnicalText(diagnosis.bottleneck.title)}</h2><p style={{fontSize:14,lineHeight:1.65,color:COLORS.inkSoft,marginTop:10}}>{simplifyTechnicalText(diagnosis.bottleneck.explanation)}</p></section>}
  <div className="split-grid" style={{marginBottom:42}}>
   <section><SectionHeader title="Fortalezas observadas"/><div className="insight-list">{diagnosis.strengths?.length?diagnosis.strengths.map((item,index)=><div className="insight" key={index}><div><h3 style={{fontSize:14,fontWeight:650}}>{simplifyTechnicalText(item.title)}</h3><p className="section-description">{simplifyTechnicalText(item.evidence)}</p></div></div>):<p className="section-description">Todavía no hay fortalezas con evidencia suficiente.</p>}</div></section>
   <section><SectionHeader title="Aspectos a resolver"/><div className="insight-list">{diagnosis.weaknesses?.length?diagnosis.weaknesses.map((item,index)=><div className="insight" key={index}><div><h3 style={{fontSize:14,fontWeight:650}}>{simplifyTechnicalText(item.title)}</h3><p className="section-description">{simplifyTechnicalText(item.evidence)}</p></div></div>):<p className="section-description">No hay otros problemas relevantes para mostrar.</p>}</div></section>
  </div>
  {diagnosis.opportunities?.length?<section className="section-rule" style={{marginBottom:42}}><SectionHeader title="Oportunidades" description="Caminos que el negocio puede aprovechar ahora."/><div className="insight-list">{diagnosis.opportunities.slice(0,3).map((item,index)=><div className="insight" key={index}><p style={{fontSize:14,lineHeight:1.6}}>{simplifyTechnicalText(item)}</p></div>)}</div></section>:null}
  {diagnosis.risks?.length?<section className="section-rule" style={{marginBottom:42}}><SectionHeader title="Riesgos a considerar" description="Señales que conviene seguir para que no frenen el avance."/><div className="insight-list">{diagnosis.risks.map((item,index)=><div className="insight" key={index}><p style={{fontSize:14,lineHeight:1.6}}>{simplifyTechnicalText(item)}</p></div>)}</div></section>:null}
  {diagnosis.priorities?.length?<section className="section-rule"><SectionHeader title="Orden recomendado" description="La secuencia sugerida para avanzar sin dispersar esfuerzo."/><div className="action-list">{diagnosis.priorities.sort((a,b)=>a.order-b.order).map((item)=><article className="action-item" key={item.order}><div className="action-number">{String(item.order).padStart(2,"0")}</div><div><h3 style={{fontSize:15,fontWeight:650}}>{simplifyTechnicalText(item.title)}</h3><p className="section-description">{simplifyTechnicalText(item.reason)}</p></div></article>)}</div></section>:null}
 </div>;
}
