"use client";
import { FormEvent, useState } from "react";
import { BrandMark, Btn, Field, TextInput } from "@/components/ui";
import { COLORS } from "@/lib/design-tokens";
export default function RegisterPage() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth/register", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, email, password }) }); if (!response.ok) { const body = await response.json(); throw new Error(body?.error?.message || "No pudimos crear tu cuenta."); } window.location.href = "/onboarding"; } catch (e) { setError(e instanceof Error ? e.message : "No pudimos crear tu cuenta."); setLoading(false); } }
  return <main className="auth-shell"><aside className="auth-brand-panel"><BrandMark inverse/><div><div className="auth-brand-line"/><h2 className="shp-display" style={{fontSize:34,lineHeight:1.16,fontWeight:600,maxWidth:430}}>Un espacio de trabajo para entender y hacer crecer tu negocio.</h2><p style={{color:"#A9ABB0",fontSize:13,lineHeight:1.65,maxWidth:380,marginTop:18}}>Tus datos, análisis y decisiones permanecen organizados en una cuenta privada.</p></div><small style={{color:"#74777E"}}>NUVRA by Shape</small></aside><section className="auth-form-panel"><div className="auth-form"><div style={{marginBottom:28}}><BrandMark/></div><div className="auth-card"><h1 className="section-title" style={{fontSize:26}}>Creá tu cuenta</h1><p className="section-description" style={{margin:"8px 0 26px"}}>Empezá con un espacio privado para tu negocio.</p><form onSubmit={submit}><Field label="Nombre"><TextInput value={name} onChange={setName} autoComplete="name" /></Field><Field label="Email"><TextInput value={email} onChange={setEmail} type="email" autoComplete="email" /></Field><Field label="Contraseña" hint="Usá al menos 10 caracteres."><TextInput value={password} onChange={setPassword} type="password" autoComplete="new-password" /></Field>{error&&<p role="alert" style={{color:COLORS.red,fontSize:13,marginBottom:16}}>{error}</p>}<Btn type="submit" full disabled={loading}>{loading?"Creando cuenta…":"Crear cuenta"}</Btn></form><p style={{textAlign:"center",fontSize:13,color:COLORS.inkSoft,marginTop:22}}>¿Ya tenés cuenta? <a href="/login" style={{color:COLORS.blue,fontWeight:600}}>Ingresar</a></p></div></div></section></main>;
}
