"use client";
import { FormEvent, useState } from "react";
import { BrandMark, Btn, Card, Field, TextInput } from "@/components/ui";
import { COLORS } from "@/lib/design-tokens";
export default function RegisterPage() {
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth/register", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ name, email, password }) }); if (!response.ok) { const body = await response.json(); throw new Error(body?.error?.message || "No pudimos crear tu cuenta."); } window.location.href = "/onboarding"; } catch (e) { setError(e instanceof Error ? e.message : "No pudimos crear tu cuenta."); setLoading(false); } }
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 24 }}><div style={{ width: "100%", maxWidth: 430 }}><div style={{ display: "flex", justifyContent: "center", marginBottom: 24 }}><BrandMark /></div><Card><h1 className="section-title" style={{ fontSize: 24 }}>Creá tu cuenta</h1><p style={{ color: COLORS.inkSoft, fontSize: 13, lineHeight: 1.6, margin: "8px 0 24px" }}>Empezá con un espacio privado para tu negocio.</p><form onSubmit={submit}><Field label="Nombre"><TextInput value={name} onChange={setName} /></Field><Field label="Email"><TextInput value={email} onChange={setEmail} type="email" /></Field><Field label="Contraseña" hint="Usá al menos 10 caracteres."><TextInput value={password} onChange={setPassword} type="password" /></Field>{error && <p style={{ color: COLORS.red, fontSize: 13, marginBottom: 16 }}>{error}</p>}<Btn type="submit" full disabled={loading}>{loading ? "Creando cuenta…" : "Crear cuenta"}</Btn></form><p style={{ textAlign: "center", fontSize: 13, color: COLORS.inkSoft, marginTop: 20 }}>¿Ya tenés cuenta? <a href="/login" style={{ color: COLORS.blue, fontWeight: 600 }}>Ingresar</a></p></Card></div></main>;
}
