"use client";
import { FormEvent, useState } from "react";
import { BrandMark, Btn, Field, TextInput } from "@/components/ui";
import { COLORS } from "@/lib/design-tokens";
export default function LoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) throw new Error("No pudimos iniciar sesión. Revisá tus datos."); window.location.href = new URLSearchParams(window.location.search).get("next") || "/dashboard"; } catch (e) { setError(e instanceof Error ? e.message : "No pudimos iniciar sesión."); setLoading(false); } }
  return <main className="auth-shell auth-shell-login"><aside className="auth-brand-panel auth-brand-panel-login"><BrandMark/><div className="auth-login-note"><div className="auth-brand-line"/><h2 className="shp-display">Claridad para decidir qué necesita tu negocio ahora.</h2><p>Diagnóstico, prioridades y un plan de acción en un solo lugar.</p></div><small>NUVRA by Shape</small></aside><section className="auth-form-panel"><div className="auth-form"><div className="auth-form-brand"><BrandMark/></div><div className="auth-card"><h1 className="section-title" style={{fontSize:26}}>Ingresá a NUVRA</h1><p className="section-description" style={{margin:"8px 0 26px"}}>Accedé a tus negocios y análisis.</p><form onSubmit={submit}><Field label="Email"><TextInput value={email} onChange={setEmail} type="email" autoComplete="email" /></Field><Field label="Contraseña"><TextInput value={password} onChange={setPassword} type="password" autoComplete="current-password" /></Field><div style={{textAlign:"right",marginTop:-12,marginBottom:18}}><a className="auth-link" href="/forgot-password">Olvidé mi contraseña</a></div>{error&&<p role="alert" style={{color:COLORS.red,fontSize:13,marginBottom:16}}>{error}</p>}<Btn type="submit" full disabled={loading}>{loading?"Ingresando…":"Ingresar"}</Btn></form><p style={{textAlign:"center",fontSize:13,color:COLORS.inkSoft,marginTop:22}}>¿Todavía no tenés cuenta? <a className="auth-link auth-link-strong" href="/register">Crear cuenta</a></p></div></div></section></main>;
}
