"use client";
import { FormEvent, useState } from "react";
import { BrandMark, Btn, Card, Field, TextInput } from "@/components/ui";
import { COLORS } from "@/lib/design-tokens";
export default function LoginPage() {
  const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [error, setError] = useState(""); const [loading, setLoading] = useState(false);
  async function submit(event: FormEvent) { event.preventDefault(); setLoading(true); setError(""); try { const response = await fetch("/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email, password }) }); if (!response.ok) throw new Error("No pudimos iniciar sesión. Revisá tus datos."); window.location.href = new URLSearchParams(window.location.search).get("next") || "/dashboard"; } catch (e) { setError(e instanceof Error ? e.message : "No pudimos iniciar sesión."); setLoading(false); } }
  return <main style={{ minHeight: "100vh", display: "grid", placeItems: "center", padding: 24 }}><div style={{ width: "100%", maxWidth: 430 }}><div style={{ display: "flex", justifyContent: "center", marginBottom: 24 }}><BrandMark /></div><Card><h1 className="section-title" style={{ fontSize: 24 }}>Ingresá a NUVRA</h1><p style={{ color: COLORS.inkSoft, fontSize: 13, lineHeight: 1.6, margin: "8px 0 24px" }}>Accedé a tus negocios y análisis.</p><form onSubmit={submit}><Field label="Email"><TextInput value={email} onChange={setEmail} type="email" /></Field><Field label="Contraseña"><TextInput value={password} onChange={setPassword} type="password" /></Field><div style={{textAlign:"right",marginTop:-12,marginBottom:16}}><a href="/forgot-password" style={{fontSize:12,color:COLORS.blue}}>Olvidé mi contraseña</a></div>{error && <p style={{ color: COLORS.red, fontSize: 13, marginBottom: 16 }}>{error}</p>}<Btn type="submit" full disabled={loading}>{loading ? "Ingresando…" : "Ingresar"}</Btn></form><p style={{ textAlign: "center", fontSize: 13, color: COLORS.inkSoft, marginTop: 20 }}>¿Todavía no tenés cuenta? <a href="/register" style={{ color: COLORS.blue, fontWeight: 600 }}>Crear cuenta</a></p></Card></div></main>;
}
