"use client";
import { useCallback, useEffect, useState } from "react";
import { Btn, StatusBadge } from "@/components/ui";
import { COLORS } from "@/lib/design-tokens";
import { PLAN_DEFINITIONS, type PlanTier } from "@/lib/plans";

interface Summary { subscription:{plan:PlanTier;status:string;trialEndsAt?:string|null;currentPeriodEnd?:string|null;cancelAtPeriodEnd:boolean};usage:Record<string,{used:number;limit:number;remaining:number;overLimit:boolean}>;developmentMode:boolean }
const labels:Record<string,string>={free:"Gratuito",trialing:"Período de prueba",active:"Activo",past_due:"Pago pendiente",canceled:"Cancelado",expired:"Vencido"};
const dashboardPlanCopy:Record<PlanTier,string>={FREE:"Para conocer el diagnóstico inicial de NUVRA.",PRO:"NUVRA piensa y planifica; vos ejecutás.",PARTNER:"Tu equipo de marketing externo."};
export function BillingPanel({organizationId}:{organizationId?:string|null}){const[data,setData]=useState<Summary>();const[busy,setBusy]=useState("");const[msg,setMsg]=useState("");const load=useCallback(async()=>{if(!organizationId)return;const response=await fetch(`/api/billing/subscription?organizationId=${encodeURIComponent(organizationId)}`);if(response.ok)setData(await response.json());else setMsg("No pudimos cargar la información del plan.");},[organizationId]);useEffect(()=>{void load()},[load]);async function action(action:string,plan?:PlanTier){if(!organizationId)return;setBusy(`${action}:${plan||""}`);setMsg("");const response=await fetch("/api/billing/subscription",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({organizationId,action,plan,billingInterval:"monthly"})});if(response.ok){setMsg("El plan se actualizó en modo de desarrollo.");await load()}else setMsg("No pudimos actualizar el plan. Verificá tus permisos.");setBusy("")}
if(!organizationId)return <p style={{color:COLORS.inkSoft}}>Seleccioná un negocio para consultar su plan.</p>;if(!data)return <div style={{height:180,borderRadius:16,background:COLORS.paperDim}}/>;const current=data.subscription.plan;const mainUsage=[["businesses","Negocios"],["monthlyAnalyses","Análisis del período"],["teamMembers","Miembros"],["monthlyReports","Reportes"]];return <div style={{display:"grid",gap:18}}><section style={{padding:24,background:"#fff",border:`1px solid ${COLORS.line}`,borderRadius:16}}><div style={{display:"flex",justifyContent:"space-between",gap:20,alignItems:"flex-start",flexWrap:"wrap"}}><div><div style={{fontSize:12,color:COLORS.inkFaint,marginBottom:6}}>PLAN ACTUAL</div><h3 style={{fontSize:25,margin:0}}>{PLAN_DEFINITIONS[current].label}</h3><div style={{marginTop:10}}><StatusBadge tone={data.subscription.status==="active"||data.subscription.status==="trialing"?"success":"neutral"}>{labels[data.subscription.status]||data.subscription.status}</StatusBadge></div></div><div style={{fontSize:13,color:COLORS.inkSoft,textAlign:"right"}}>{data.subscription.trialEndsAt&&<div>Prueba hasta {new Date(data.subscription.trialEndsAt).toLocaleDateString("es-AR")}</div>}{data.subscription.currentPeriodEnd&&<div>Período hasta {new Date(data.subscription.currentPeriodEnd).toLocaleDateString("es-AR")}</div>}{data.developmentMode&&<div style={{marginTop:6}}>Modo de desarrollo · sin cargos reales</div>}</div></div>{msg&&<p style={{fontSize:13,color:COLORS.inkSoft,marginTop:16}}>{msg}</p>}</section>
<section style={{padding:24,background:"#fff",border:`1px solid ${COLORS.line}`,borderRadius:16}}><h3 style={{fontSize:17,marginBottom:16}}>Uso y límites</h3><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}>{mainUsage.map(([key,label])=>{const value=data.usage[key];return value?<div key={key} style={{padding:14,borderRadius:12,background:value.overLimit?COLORS.amberSoft:COLORS.paperDim}}><div style={{fontSize:12,color:COLORS.inkSoft}}>{label}</div><div style={{fontSize:20,fontWeight:700,marginTop:5}}>{value.used} <span style={{fontSize:12,fontWeight:400,color:COLORS.inkFaint}}>de {value.limit}</span></div><div style={{fontSize:11,color:COLORS.inkFaint,marginTop:4}}>{value.overLimit?"Supera el límite actual. Tus datos se conservan.":`${value.remaining} disponibles`}</div></div>:null})}</div></section>
{data.developmentMode&&<section style={{padding:24,background:"#fff",border:`1px solid ${COLORS.line}`,borderRadius:16}}><h3 style={{fontSize:17,marginBottom:6}}>Cambiar de plan</h3><p style={{fontSize:13,color:COLORS.inkSoft,marginBottom:18}}>Los precios definitivos todavía no están publicados. Estas acciones usan el simulador interno.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}>{(["FREE","PRO","PARTNER"] as PlanTier[]).map(tier=><div key={tier} style={{padding:16,border:`1px solid ${current===tier?COLORS.blue:COLORS.line}`,borderRadius:12}}><strong>{PLAN_DEFINITIONS[tier].label}</strong><p style={{fontSize:12,color:COLORS.inkSoft,minHeight:38,lineHeight:1.5}}>{dashboardPlanCopy[tier]}</p><Btn full variant={current===tier?"ghost":"primary"} disabled={current===tier||Boolean(busy)} onClick={()=>void action("change_plan",tier)}>{current===tier?"Plan actual":tier==="FREE"?"Cambiar a Free":"Elegir plan"}</Btn>{tier==="PRO"&&current==="FREE"&&<button type="button" disabled={Boolean(busy)} onClick={()=>void action("start_trial","PRO")} style={{width:"100%",marginTop:9,border:0,background:"transparent",color:COLORS.blueDeep,cursor:"pointer",fontSize:12}}>Probar Pro</button>}</div>)}</div>{current!=="FREE"&&<div style={{display:"flex",gap:10,marginTop:18}}>{data.subscription.cancelAtPeriodEnd?<Btn variant="ghost" onClick={()=>void action("reactivate")}>Reactivar suscripción</Btn>:<Btn variant="ghost" onClick={()=>void action("cancel")}>Cancelar al final del período</Btn>}</div>}</section>}</div>}
