import Link from "next/link";
import { PLAN_DEFINITIONS,getPlanFeatures,type PlanTier } from "@/lib/plans";
import { BILLING_CONFIG } from "@/services/billing/config";
import { COLORS } from "@/lib/design-tokens";
import { BrandMark } from "@/components/ui";
export default function PricingPage(){
 const tiers:PlanTier[]=["FREE","PRO","PARTNER"];
 return <main style={{minHeight:"100vh",padding:"28px clamp(20px,4vw,52px) 72px"}}><nav style={{display:"flex",justifyContent:"space-between",alignItems:"center",maxWidth:1120,margin:"0 auto 80px"}}><BrandMark/><Link href="/register" className="btn btn-primary btn-sm">Crear cuenta</Link></nav><div style={{maxWidth:1120,margin:"0 auto"}}><header style={{maxWidth:720,marginBottom:52}}><div className="page-eyebrow">Planes</div><h1 className="page-title" style={{fontSize:"clamp(38px,5vw,58px)"}}>Una estructura para cada etapa</h1><p className="page-subtitle" style={{fontSize:16,maxWidth:620}}>Empezá con un diagnóstico base y ampliá capacidades cuando necesites gestionar más marketing, negocios o clientes.</p></header><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(270px,1fr))",borderTop:"1px solid "+COLORS.lineStrong}}>{tiers.map((tier)=>{const plan=PLAN_DEFINITIONS[tier];return <article key={tier} style={{padding:"30px 28px 34px 0",borderBottom:"1px solid "+COLORS.line,minHeight:380}}><h2 className="section-title" style={{fontSize:24}}>{plan.label}</h2><div style={{fontSize:18,fontWeight:650,marginTop:10}}>{BILLING_CONFIG.displayPrices[tier]}</div><p className="section-description" style={{minHeight:72,marginTop:12}}>{plan.audience}</p><ul style={{paddingLeft:18,display:"grid",gap:10,fontSize:13,lineHeight:1.5,marginTop:20}}>{plan.highlights.map((item)=><li key={item}>{item}</li>)}</ul><div style={{borderTop:"1px solid "+COLORS.line,marginTop:24,paddingTop:14,fontSize:12,color:COLORS.inkFaint}}>{getPlanFeatures(tier).length} capacidades incluidas</div></article>})}</div></div></main>;
}
