"use client";
import { CSSProperties, useState } from "react";
import { useDashboardData } from "@/lib/use-dashboard-data";
import { COLORS } from "@/lib/design-tokens";
import { Btn, Card, DemoBadge, EmptyState, ErrorState, PageHeader, PageSkeleton, ScoreRing, SectionHeader, SourceStatus } from "@/components/ui";
import { formatActionForBusiness, getFriendlyDimensionName, presentOpportunity, presentProblem, simplifyTechnicalText } from "@/lib/simple-language-presenter";
export default function DashboardHomePage(){
 const {business,intelligence,score,diagnosis,actions,loading,error,isDemo}=useDashboardData(); const [showEvidence,setShowEvidence]=useState(false);
 if(loading)return <PageSkeleton/>; if(error)return <ErrorState message={error==="Sin negocio"?"Primero necesitás registrar un negocio para ver su estado.":error} onRetry={()=>{window.location.href="/onboarding"}}/>;
 const limitedInformation=!intelligence||intelligence.coverage<70;
 const displayedProblems=[diagnosis?.bottleneck?.title?presentProblem({title:diagnosis.bottleneck.title,explanation:diagnosis.bottleneck.explanation,objective:business.objetivo}):null,...(diagnosis?.weaknesses||[]).map((problem)=>presentProblem({title:problem.title,explanation:problem.evidence,objective:business.objetivo}))].filter((problem):problem is ReturnType<typeof presentProblem>=>Boolean(problem)).filter((problem,index,all)=>all.findIndex((item)=>item.title===problem.title)===index).slice(0,2);
 const opportunities=(diagnosis?.opportunities||[]).map(presentOpportunity).filter((item,index,all)=>item&&all.indexOf(item)===index&&!displayedProblems.some((problem)=>problem.title===item)).slice(0,3); const priorityActions=actions.filter((action)=>!action.done).slice(0,3);
 const sourceStatus=(key:"web"|"search"|"competitor"|"external_mentions")=>intelligence?.sourceStatuses?.[key]==="evaluated"?"ready":intelligence?.sourceStatuses?.[key]==="unavailable"?"unavailable":"pending";
 return <div className="page-container">
  <PageHeader eyebrow="Estado del negocio" title={business.nombre} subtitle={<>{isDemo&&<DemoBadge style={{marginRight:8}}/>}<span>{business.rubro}</span>{business.objetivo&&<span style={{display:"block",marginTop:3}}>Objetivo actual: {business.objetivo}</span>}</>} action={<Btn variant="ghost" size="sm" onClick={()=>{window.location.href="/dashboard/acciones"}}>Ver plan de acción</Btn>}/>
  {limitedInformation&&<div style={{borderLeft:"2px solid "+COLORS.blue,padding:"11px 16px",marginBottom:30,color:COLORS.inkSoft,fontSize:12.5,lineHeight:1.55}}>Este resultado se calcula con la información disponible hasta el momento. Si se obtiene más información, el puntaje y las recomendaciones pueden ajustarse.</div>}
  <section className="metric-grid" style={{marginBottom:42}}><div className="score-indicator"><ScoreRing value={score?.total??40} status="COMPLETO"/><div><h2 className="section-title">Nuvra Score</h2><p className="section-description">Una lectura general de qué tan preparado está el negocio para avanzar hacia {business.objetivo?.toLowerCase()||"su objetivo"}.</p></div></div><div><SectionHeader title="Tu negocio, área por área" description="Los marcadores muestran dónde hay más solidez y dónde conviene intervenir."/>
   {score?.dimensions?.length?<div>{score.dimensions.map((dimension)=>{const points=dimension.points??40;return <div className="diagnostic-row" key={dimension.slug}><span style={{fontSize:12.5}}>{getFriendlyDimensionName(dimension.slug,dimension.name)}</span><div className="diagnostic-track" style={{"--value":points} as CSSProperties}/><strong style={{fontSize:12,textAlign:"right"}}>{points}</strong></div>})}</div>:<EmptyState title="Preparando los puntajes" description="NUVRA está reuniendo la información necesaria para completar esta lectura."/>}</div></section>
  <section style={{marginBottom:42}}><SectionHeader title="Lo más importante que encontramos" description="La conclusión que más puede afectar el objetivo actual."/>
   {displayedProblems.length?<div className="strategic-callout"><h3 style={{fontSize:18,lineHeight:1.35,fontWeight:650}}>{displayedProblems[0].title}</h3><p style={{fontSize:14,lineHeight:1.65,color:COLORS.inkSoft,marginTop:9}}>{displayedProblems[0].explanation}</p><p style={{fontSize:13,lineHeight:1.55,marginTop:14}}><strong>Cómo afecta tu objetivo: </strong>{displayedProblems[0].whyItMatters.replace(/^Esto importa porque\s*/i,"")}</p>{displayedProblems[1]&&<p style={{fontSize:12.5,color:COLORS.inkSoft,marginTop:18,paddingTop:15,borderTop:"1px solid "+COLORS.line}}><strong>También observamos: </strong>{displayedProblems[1].title}</p>}</div>:<EmptyState title="Preparando la prioridad principal" description="Al sumar información del negocio podremos sostener una conclusión concreta."/>}</section>
  <div className="content-grid"><div className="stack"><section><SectionHeader title="Qué haríamos primero" description="Un plan breve, ordenado por impacto y factibilidad."/>
   {priorityActions.length?<div className="action-list">{priorityActions.map((action,index)=>{const item=formatActionForBusiness(action);return <article className="action-item" key={item.id}><div className="action-number">{String(index+1).padStart(2,"0")}</div><div><h3 style={{fontSize:15,fontWeight:650}}>{item.title}</h3><p style={{fontSize:13,lineHeight:1.6,color:COLORS.inkSoft,marginTop:7}}>{item.whatToDo}</p><div className="action-meta"><span>Resultado esperado: {item.expectedResult}</span></div></div></article>})}<Btn variant="ghost" size="sm" onClick={()=>{window.location.href="/dashboard/acciones"}} style={{marginTop:18}}>Ver todas las acciones</Btn></div>:<EmptyState title="Sin acciones disponibles" description="Las acciones aparecerán cuando haya evidencia suficiente para recomendar un cambio concreto."/>}</section></div>
   <aside className="stack"><section><SectionHeader title="Oportunidades" description="Tres caminos concretos para aprovechar."/>
    {opportunities.length?<div className="insight-list">{opportunities.map((opportunity,index)=><div className="insight" key={index}><p style={{fontSize:13,lineHeight:1.55}}>{opportunity}</p></div>)}</div>:<p className="section-description">Conectar tus canales permitirá encontrar oportunidades concretas para el objetivo actual.</p>}</section>
    <Card><SectionHeader title="Cómo llegamos a esto" description="Fuentes y evidencia, disponibles cuando quieras revisarlas." action={<Btn variant="ghost" size="sm" onClick={()=>setShowEvidence((value)=>!value)}>{showEvidence?"Ocultar":"Ver evidencia"}</Btn>}/>
     {showEvidence&&<div><SourceStatus label="Sitio web" detail={intelligence?.sourceMessages?.web||(business.webUrl?"Sitio identificado":"NUVRA buscó alternativas públicas")} status={sourceStatus("web")}/><SourceStatus label="Búsqueda" detail={intelligence?.sourceMessages?.search||"Buscando presencia pública"} status={sourceStatus("search")}/><SourceStatus label="Competencia" detail={intelligence?.sourceMessages?.competitor||"Sin evidencia validada"} status={sourceStatus("competitor")}/><SourceStatus label="Menciones externas" detail={intelligence?.sourceMessages?.external_mentions||"Sin resultados analizados"} status={sourceStatus("external_mentions")}/><SourceStatus label="Instagram" detail={intelligence?.sourceStatuses?.instagram==="evaluated"?"Perfil público identificado y revisado":business.instagramHandle||intelligence?.discoveredInstagram?"Perfil identificado; información pública limitada":"No encontramos un perfil verificable"} status={intelligence?.sourceStatuses?.instagram==="evaluated"?"ready":business.instagramHandle||intelligence?.discoveredInstagram?"partial":"pending"}/>{diagnosis?.strengths?.length?<div style={{marginTop:20}}><h3 style={{fontSize:13,fontWeight:650}}>Fortalezas observadas</h3>{diagnosis.strengths.slice(0,3).map((strength,index)=><p key={index} className="section-description" style={{paddingTop:10}}>{simplifyTechnicalText(strength.title)}</p>)}</div>:null}</div>}</Card></aside>
  </div>
 </div>;
}
