"use client";
import { useDashboardData } from "@/lib/use-dashboard-data";
import { COLORS } from "@/lib/design-tokens";
import { Btn, Card, CoverageBar, DemoBadge, EmptyState, ErrorState, PageSkeleton, ScoreRing, StatusBadge } from "@/components/ui";
import { simplifyTechnicalText, formatActionForBusiness, getFriendlyDimensionName } from "@/lib/simple-language-presenter";

function SourceRow({ label, detail, status }: { label: string; detail: string; status: "ready" | "partial" | "pending" }) {
  const config = status === "ready" ? { tone: "success" as const, text: "Analizada" } : status === "partial" ? { tone: "warning" as const, text: "Parcial" } : { tone: "neutral" as const, text: "Pendiente" };
  return <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between", gap: 18, padding: "13px 0", borderBottom: `1px solid ${COLORS.line}` }}><div><div style={{ fontSize: 13, fontWeight: 600 }}>{label}</div><div style={{ fontSize: 12, color: COLORS.inkFaint, marginTop: 3 }}>{detail}</div></div><StatusBadge tone={config.tone}>{config.text}</StatusBadge></div>;
}

export default function DashboardHomePage() {
  const { business, intelligence, score, diagnosis, actions, loading, error, isDemo } = useDashboardData();
  if (loading) return <PageSkeleton />;
  if (error) return <ErrorState message={error === "Sin negocio" ? "Primero necesitás registrar un negocio para ver su estado." : error} onRetry={() => { window.location.href = "/onboarding"; }} />;

  const coverage = intelligence?.coverage ?? score?.coverage ?? 0;
  const scoreStatus: "PENDIENTE" | "PRELIMINAR" | "COMPLETO" = !score || score.total === null ? "PENDIENTE" : coverage >= 75 ? "COMPLETO" : "PRELIMINAR";
  const scoreTone = scoreStatus === "COMPLETO" ? "success" : scoreStatus === "PRELIMINAR" ? "warning" : "neutral";
  const primaryProblems = diagnosis?.weaknesses?.slice(0, 3) || [];
  const opportunities = diagnosis?.opportunities?.slice(0, 3) || [];
  const priorityActions = actions.filter((action) => !action.done).slice(0, 3);

  return <div className="page-container">
    <header className="page-header"><div><div className="page-eyebrow">Estado general</div><h1 className="page-title">{business.nombre}</h1><p className="page-subtitle">{isDemo && <DemoBadge style={{ marginRight: 8 }} />}{business.rubro}{business.objetivo ? ` · Objetivo: ${business.objetivo}` : ""}</p></div><Btn variant="ghost" size="sm" onClick={() => { window.location.href = "/dashboard/acciones"; }}>Ver plan de acción</Btn></header>

    <div className="metric-grid" style={{ marginBottom: 16 }}>
      <Card style={{ display: "flex", alignItems: "center", gap: 28, minHeight: 228 }}><ScoreRing value={score?.total ?? null} status={scoreStatus} /><div style={{ flex: 1 }}><StatusBadge tone={scoreTone}>{scoreStatus}</StatusBadge><h2 className="section-title" style={{ marginTop: 14 }}>Nuvra Score</h2><p style={{ fontSize: 13, color: COLORS.inkSoft, lineHeight: 1.55, margin: "7px 0 20px" }}>{scoreStatus === "COMPLETO" ? "El puntaje cuenta con una base amplia de información pública." : scoreStatus === "PRELIMINAR" ? "Es una primera lectura. Puede cambiar al sumar fuentes." : "Todavía no hay información suficiente para calcularlo."}</p><CoverageBar value={coverage} label="Información disponible" /></div></Card>
      <Card><div className="page-eyebrow">Lectura por área</div><h2 className="section-title" style={{ marginBottom: 20 }}>Dónde estás mejor y dónde actuar</h2>{score?.dimensions?.length ? <div className="stack" style={{ gap: 14 }}>{score.dimensions.map((dimension) => { const valid = dimension.points !== null && dimension.points !== undefined && dimension.points >= 0; const points = valid ? dimension.points : 0; return <div key={dimension.slug}><div style={{ display: "flex", justifyContent: "space-between", gap: 12, marginBottom: 7, fontSize: 12 }}><span>{getFriendlyDimensionName(dimension.slug, dimension.name)}</span><span style={{ color: valid ? COLORS.ink : COLORS.inkFaint, fontWeight: 600 }}>{valid ? `${points}/100` : "Sin datos suficientes"}</span></div><div style={{ height: 6, background: COLORS.paperDim, borderRadius: 99, overflow: "hidden" }}><div style={{ height: "100%", width: `${valid ? points : 0}%`, background: points >= 65 ? COLORS.olive : points >= 45 ? COLORS.blue : COLORS.red, borderRadius: 99 }} /></div></div>; })}</div> : <EmptyState title="Todavía no hay una lectura por área" description="Cuando termine el primer análisis vas a ver qué partes están más fuertes y cuáles necesitan atención." />}</Card>
    </div>

    <div className="content-grid" style={{ marginBottom: 16 }}><div className="stack">
      <Card><div className="page-eyebrow">Prioridad</div><h2 className="section-title" style={{ marginBottom: 16 }}>Principales problemas</h2>{diagnosis?.bottleneck?.title && <div style={{ padding: 16, borderRadius: 12, background: COLORS.redSoft, marginBottom: 12 }}><div style={{ fontSize: 13, fontWeight: 650, marginBottom: 5 }}>{simplifyTechnicalText(diagnosis.bottleneck.title)}</div><div style={{ fontSize: 13, lineHeight: 1.55, color: COLORS.inkSoft }}>{simplifyTechnicalText(diagnosis.bottleneck.explanation)}</div></div>}{primaryProblems.length ? <div className="stack" style={{ gap: 10 }}>{primaryProblems.map((problem, index) => <div key={`${problem.title}-${index}`} style={{ padding: "12px 0", borderBottom: `1px solid ${COLORS.line}` }}><div style={{ fontSize: 13, fontWeight: 600 }}>{simplifyTechnicalText(problem.title)}</div><div style={{ fontSize: 12, color: COLORS.inkSoft, lineHeight: 1.55, marginTop: 4 }}>{simplifyTechnicalText(problem.evidence)}</div></div>)}</div> : !diagnosis?.bottleneck?.title && <EmptyState title="Sin problemas confirmados" description="No hay evidencia suficiente para señalar un problema principal todavía." />}</Card>
      <Card><div className="page-eyebrow">Próximos pasos</div><h2 className="section-title" style={{ marginBottom: 16 }}>Acciones prioritarias</h2>{priorityActions.length ? <div className="stack" style={{ gap: 10 }}>{priorityActions.map((action, index) => { const item = formatActionForBusiness(action); return <div key={item.id} style={{ display: "grid", gridTemplateColumns: "28px 1fr auto", gap: 12, alignItems: "start", padding: "14px 0", borderBottom: `1px solid ${COLORS.line}` }}><div style={{ width: 27, height: 27, display: "grid", placeItems: "center", borderRadius: 8, background: COLORS.ink, color: "#fff", fontSize: 11, fontWeight: 700 }}>{index + 1}</div><div><div style={{ fontSize: 13, fontWeight: 650 }}>{item.whatToDo}</div><div style={{ fontSize: 12, lineHeight: 1.5, color: COLORS.inkSoft, marginTop: 4 }}>{item.expectedResult}</div></div><StatusBadge tone={item.impact.toLowerCase().includes("alto") ? "info" : "neutral"}>{item.impact}</StatusBadge></div>; })}<Btn variant="ghost" size="sm" onClick={() => { window.location.href = "/dashboard/acciones"; }} style={{ justifySelf: "start", marginTop: 4 }}>Ver todas las acciones</Btn></div> : <EmptyState title="Sin acciones disponibles" description="Las acciones aparecerán cuando haya evidencia suficiente para recomendar un cambio concreto." />}</Card>
    </div><div className="stack">
      <Card><div className="page-eyebrow">Potencial</div><h2 className="section-title" style={{ marginBottom: 16 }}>Oportunidades</h2>{opportunities.length ? <div className="stack" style={{ gap: 10 }}>{opportunities.map((opportunity, index) => <div key={`${opportunity}-${index}`} style={{ display: "flex", gap: 10, paddingBottom: 12, borderBottom: `1px solid ${COLORS.line}` }}><div style={{ width: 7, height: 7, borderRadius: 99, background: COLORS.olive, marginTop: 6, flexShrink: 0 }} /><p style={{ fontSize: 13, lineHeight: 1.55 }}>{simplifyTechnicalText(opportunity)}</p></div>)}</div> : <p style={{ color: COLORS.inkSoft, fontSize: 13, lineHeight: 1.6 }}>Todavía no hay evidencia suficiente para confirmar oportunidades concretas.</p>}</Card>
      <Card><div className="page-eyebrow">Base del análisis</div><h2 className="section-title">Fuentes</h2><div style={{ marginTop: 8 }}><SourceRow label="Sitio web" detail={business.webUrl ? "Sitio identificado" : "No informado"} status={business.webUrl ? "ready" : "pending"} /><SourceRow label="Competencia" detail={intelligence?.competitorSummary ? `${intelligence.competitorSummary.totalValidated} empresas verificadas` : "Sin evidencia validada"} status={intelligence?.competitorSummary ? intelligence.competitorSummary.totalValidated > 0 ? "ready" : "partial" : "pending"} /><SourceRow label="Menciones externas" detail={intelligence?.externalMentionsSummary ? `${intelligence.externalMentionsSummary.totalAccepted} menciones útiles` : "Sin resultados analizados"} status={intelligence?.externalMentionsSummary ? intelligence.externalMentionsSummary.totalAccepted > 0 ? "ready" : "partial" : "pending"} /><SourceRow label="Instagram" detail={business.instagramHandle ? "Cuenta informada; conexión pendiente" : "Cuenta no conectada"} status="pending" /></div></Card>
    </div></div>
  </div>;
}
